use utils in knative/pkg
knative-sandbox/eventing-autoscaler-keda pull request #21
Opened 2020-09-30 09:23 UTC by runzexia

Signed-off-by: runzexia <root@junwuhui.cn>

2020-09-30 14:38 UTC, zroubalik requested changes

2020-09-30 14:38 UTC, zroubalik commented on pkg/reconciler/kafka/kafka.go
> +	return kmeta.ChildName(fmt.Sprintf("kafkasource-%s-", src.Name), string(src.GetUID()))
The Kafka Source is still using `utils.GenerateFixedName()` see: https://github.com/knative/eventing-contrib/blob/315af7ccf3a0d519c04e4bc9407feb8f8a125c43/kafka/source/pkg/reconciler/source/resources/receive_adapter.go#L84
So we should always use the same, to target the same deployment.
Am I missing anything?

2020-09-30 14:38 UTC, zroubalik commented on pkg/reconciler/source/source.go
> +			if err := r.kubeClient.AppsV1().Deployments(obj.GetNamespace()).Delete(ctx, deprecatedName, metav1.DeleteOptions{}); err != nil && !apierrors.IsNotFound(err) {
I don't think we should delete or modify the Deployment (Adapter) from this controller. This should be handled by Kafka Source Controller

2020-09-30 14:43 UTC, runzexia commented on pkg/reconciler/source/source.go
> +			if err := r.kubeClient.AppsV1().Deployments(obj.GetNamespace()).Delete(ctx, deprecatedName, metav1.DeleteOptions{}); err != nil && !apierrors.IsNotFound(err) {
ok

2020-09-30 14:46 UTC, mattmoor reviewed
<!--gotool-bot-->
Produced via:
  `gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
  `goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`

2020-09-30 14:46 UTC, mattmoor commented on pkg/reconciler/source/source.go
> +
<!--gotool-bot-->
Format Go code:
```suggestion

```

2020-09-30 14:49 UTC, runzexia commented on pkg/reconciler/kafka/kafka.go
> +	return kmeta.ChildName(fmt.Sprintf("kafkasource-%s-", src.Name), string(src.GetUID()))
create https://github.com/knative/eventing-contrib/pull/1619/ to handle Kafka Source

2020-09-30 15:14 UTC, zroubalik commented on pkg/reconciler/kafka/kafka.go
> +	return kmeta.ChildName(fmt.Sprintf("kafkasource-%s-", src.Name), string(src.GetUID()))
OK, we should wait for that PR to be merged in eventing-contrib

2020-10-05 16:19 UTC, n3wscott reviewed
/lgtm
/approve

2020-10-05 16:20 UTC, n3wscott commented
/hold for https://github.com/knative/eventing-contrib/pull/1619#pullrequestreview-502219256

2020-10-14 05:47 UTC, runzexia commented
@n3wscott @zroubalik 
Should we pin kafkasource to https://github.com/knative-sandbox/eventing-kafka?
If it's need, I can help

2020-10-14 12:05 UTC, zroubalik commented
> @n3wscott @zroubalik
> Should we pin kafkasource to https://github.com/knative-sandbox/eventing-kafka?
> If it's need, I can help

@runzexia is that repo the proper source of KafkaSource now? I haven't followed the Kafka related changes recently.

2020-10-14 12:16 UTC, runzexia commented
> > @n3wscott @zroubalik
> > Should we pin kafkasource to https://github.com/knative-sandbox/eventing-kafka?
> > If it's need, I can help
> 
> @runzexia is that repo the proper source of KafkaSource now? I haven't followed the Kafka related changes recently.

https://github.com/knative/eventing-contrib/pull/1619#issuecomment-707561521
yes, as mentioned

2020-10-14 12:20 UTC, zroubalik commented
> > @runzexia is that repo the proper source of KafkaSource now? I haven't followed the Kafka related changes recently.
> 
> [knative/eventing-contrib#1619 (comment)](https://github.com/knative/eventing-contrib/pull/1619#issuecomment-707561521)
> yes, as mentioned

@runzexia thanks, we should change that as well then 👍  Would be great if you can look at that.

2020-10-14 12:21 UTC, runzexia commented
> @runzexia thanks, we should change that as well then 👍 Would be great if you can look at that.

ok will try it ☺️

2020-10-15 08:24 UTC, zroubalik commented
/unhold

2020-10-15 08:24 UTC, zroubalik commented
/lgtm
/approve

2020-10-15 08:26 UTC, merged